---
- name: Provision EC2 and install Docker + Nginx
  hosts: localhost
  gather_facts: no
  vars:
    key_name: your-key
    region: us-east-1
    image: ami-0c94855ba95c71c99  # Amazon Linux 2
    instance_type: t2.micro
    security_group: nginx-sg
    instance_name: AnsibleDockerHost
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        instance_tags:
          Name: "{{ instance_name }}"
        count: 1
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: web
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      loop: "{{ ec2.instances }}"
